# Getting Started
## Tensors

### Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [1]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.1564,  0.0000]])


Construct a randomly initialized matrix:

In [4]:
x = torch.rand(5,3)
print(x)

tensor([[ 0.7826,  0.9596,  0.9496],
        [ 0.3222,  0.2861,  0.9050],
        [ 0.2968,  0.6558,  0.5931],
        [ 0.8386,  0.2916,  0.9406],
        [ 0.1843,  0.7379,  0.2227]])


Construct a matrix filled zeros and of dtype long

In [5]:
x = torch.zeros(5,3, dtype= torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


Construct a matrix filled zeros and of dtype long:

In [7]:
x = torch.tensor([5.5,3])
print(x)

tensor([ 5.5000,  3.0000])


create a tensor basing on existing tensor.

In [16]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)


In [17]:
x = torch.rand_like(x,dtype=torch.float)
print(x)

tensor([[ 0.3532,  0.5032,  0.4065],
        [ 0.8379,  0.9701,  0.0887],
        [ 0.3357,  0.6803,  0.8725],
        [ 0.2950,  0.1753,  0.5791],
        [ 0.7991,  0.6145,  0.4473]])


Get its size

In [18]:
print(x.size())

torch.Size([5, 3])


## Operations

In [19]:
y = torch.rand(5,3)
print(x+y)

tensor([[ 1.1740,  0.9614,  1.2408],
        [ 1.4621,  1.8897,  1.0717],
        [ 0.7046,  1.6670,  1.5575],
        [ 0.7398,  0.5068,  1.4299],
        [ 1.7351,  0.8948,  0.5444]])


In [20]:
print(torch.add(x,y))

tensor([[ 1.1740,  0.9614,  1.2408],
        [ 1.4621,  1.8897,  1.0717],
        [ 0.7046,  1.6670,  1.5575],
        [ 0.7398,  0.5068,  1.4299],
        [ 1.7351,  0.8948,  0.5444]])


Addition: providing an output tensor as argument